// =============================================================================
// SCHEMAS EXPORTS
// =============================================================================

export {
  // Enum Arrays (for select options)
  TTT_HYPOTONISANT_VALUES,
  HIRSCHBERG_TYPES,
  HIRSCHBERG_DETAIL_VALUES,
  STEREOSCOPY_LANG_VALUES,
  REFLEX_VALUES,
  LATERALITY_VALUES,
  COVER_TEST_TYPES,
  COVER_TEST_DIRECTIONS,
  CLINICAL_CHECK_VALUES,
  EYE_SYMPTOMS,
  EYE_OPTIONS,
  DIPLOPIE_TYPES,
  PBO_VALUES,
  SEGMENT_STATUS,
  CORNEE_VALUES,
  PROFONDEUR_VALUES,
  TRANSPARENCE_VALUES,
  TYPE_ANOMALIE_VALUES,
  QUANTITE_ANOMALIE_VALUES,
  PUPILLE_VALUES,
  AXE_VISUEL_VALUES,
  RPM_VALUES,
  IRIS_VALUES,
  CRISTALLIN_VALUES,
  POSITION_CRISTALLIN_VALUES,
  VITRE_VALUES,
  PAPILLE_VALUES,
  MACULA_VALUES,
  RETINIEN_VALUES,
  VAISSEAUX_VALUES,
  VISION_APTITUDE,
  // Enum Schemas
  TttHypotonisantEnum,
  HirschbergTypeEnum,
  HirschbergDetailEnum,
  StereoscopyLangEnum,
  ReflexEnum,
  LateralityEnum,
  CoverTestTypeEnum,
  CoverTestDirectionEnum,
  ClinicalCheckEnum,
  EyeSymptomEnum,
  EyeEnum,
  DiplopieTypeEnum,
  PboEnum,
  SegmentEnum,
  CorneeEnum,
  ProfondeurEnum,
  TransparenceEnum,
  TypeAnomalieValueEnum,
  QuantiteAnomalieEnum,
  PupilleEnum,
  AxeVisuelEnum,
  RpmEnum,
  IrisEnum,
  CristallinEnum,
  PositionCristallinEnum,
  VitreEnum,
  PapilleEnum,
  MaculaEnum,
  RetinienPeripheriqueEnum,
  VaissauxEnum,
  VisionAptitudeEnum,
  SectionEnum,
  // Technical Schemas
  VisualAcuitySchema,
  RefractionSchema,
  OcularTensionSchema,
  PachymetrySchema,
  VisionBinoculaireSchema,
  ClinicalCheckChildSchema,
  TechnicalExamSchema,
  // Clinical Schemas
  PlaintesSchema,
  PerimetrySchema,
  BiomicroscopyAnteriorSchema,
  BiomicroscopyPosteriorSchema,
  BpSupSchema,
  ConclusionSchema,
  ClinicalExamSchema,
  // Examen Adulte Schemas
  ExamenAdultSchema,
  ExamenAdultCreateSchema,
  ExamenAdultDetailSchema,
  ExamenAdultProgressiveSchema,
  ExamenAdultCompleteSchema,
  PaginatedExamenAdultListSchema,
  PatientNestedSchema,
  // Examen Enfant Schemas
  ExamenChildSchema,
  ExamenChildCreateSchema,
  ExamenChildDetailSchema,
  PaginatedExamenChildListSchema,
  // Pièces Jointes Schemas
  ExamenSupplementaireListSchema,
  ExamenSupplementaireSchema,
  ExamenSupplementaireCreateSchema,
  PaginatedExamenSupplementaireListSchema,
  // Default Values
  defaultBiomicroscopyAnterior,
  defaultBiomicroscopyPosterior,
  // Form Values Types (exported from schemas)
  type VisualAcuityFormValues,
  type RefractionFormValues,
  type OcularTensionFormValues,
  type PachymetryFormValues,
  type TechnicalExamFormValues,
  type PlaintesFormValues,
  type PerimetryFormValues,
  type BiomicroscopyAnteriorFormValues,
  type BiomicroscopyPosteriorFormValues,
  type ConclusionFormValues,
  type ClinicalExamFormValues,
  type VisionBinoculaireFormValues,
  type ClinicalCheckChildFormValues,
} from './schemas';

// =============================================================================
// TYPES EXPORTS
// =============================================================================

export type {
  // Enum Types
  TttHypotonisant,
  HirschbergType,
  StereoscopyLang,
  Reflex,
  Laterality,
  CoverTestType,
  CoverTestDirection,
  ClinicalCheck,
  EyeSymptom,
  Eye,
  DiplopieType,
  Pbo,
  Segment,
  Cornee,
  Profondeur,
  Transparence,
  TypeAnomalieValue,
  QuantiteAnomalie,
  Pupille,
  AxeVisuel,
  Rpm,
  Iris,
  Cristallin,
  PositionCristallin,
  Vitre,
  Papille,
  Macula,
  RetinienPeripherique,
  Vaissaux,
  VisionAptitude,
  Section,
  // Technical Types
  VisualAcuity,
  Refraction,
  OcularTension,
  Pachymetry,
  VisionBinoculaire,
  ClinicalCheckChild,
  TechnicalExam,
  // Clinical Types
  Plaintes,
  Perimetry,
  BiomicroscopyAnterior,
  BiomicroscopyPosterior,
  BpSup,
  Conclusion,
  ClinicalExam,
  // Examen Adulte Types
  ExamenAdult,
  ExamenAdultCreate,
  ExamenAdultDetail,
  ExamenAdultProgressive,
  ExamenAdultComplete,
  ExamenAdultAddTechnical,
  ExamenAdultAddClinical,
  PaginatedExamenAdultList,
  PatientNested,
  // Examen Enfant Types
  ExamenChild,
  ExamenChildCreate,
  ExamenChildDetail,
  PaginatedExamenChildList,
  TechnicalExamenCreate,
  ClinicalExamenCreate,
  // Pièces Jointes Types
  ExamenSupplementaireList,
  ExamenSupplementaire,
  ExamenSupplementaireCreate,
  PaginatedExamenSupplementaireList,
  // Query Params
  ExamsQueryParams,
} from './types';

// =============================================================================
// API SCHEMAS EXPORTS - Pour les réponses API du backend
// =============================================================================

export {
  // Patient API
  PatientNestedApiSchema,
  // Technical API
  VisualAcuityApiSchema,
  RefractionApiSchema,
  OcularTensionApiSchema,
  PachymetryApiSchema,
  TechnicalExamenApiSchema,
  // Clinical API
  PlaintesApiSchema,
  BiomicroscopyAnteriorApiSchema,
  BiomicroscopyPosteriorApiSchema,
  EyeExamApiSchema,
  PerimetryApiSchema,
  ConclusionApiSchema,
  ClinicalExamenApiSchema,
  // Examen Adulte API
  ExamenAdultDetailApiSchema,
  // Examen Enfant API
  VisionBinoculaireApiSchema,
  ExamenChildDetailApiSchema,
  // Types
  type PatientNestedApi,
  type VisualAcuityApi,
  type RefractionApi,
  type OcularTensionApi,
  type PachymetryApi,
  type TechnicalExamenApi,
  type PlaintesApi,
  type BiomicroscopyAnteriorApi,
  type BiomicroscopyPosteriorApi,
  type EyeExamApi,
  type PerimetryApi,
  type ConclusionApi,
  type ClinicalExamenApi,
  type ExamenAdultDetailApi,
  type VisionBinoculaireApi,
  type ExamenChildDetailApi,
} from './api-schemas';
